services:
  app:
    image: ghcr.io/lei-rr/infinite-canvas:latest
    container_name: infinite-canvas
    ports:
      - "${PORT:-3011}:3000"
    restart: always
    volumes:
      - ./data/images:/app/data/images
    env_file:
      - .env
